release_branches:
  master:
    - ovirt-master
  ovirt-4.4.8:
    - ovirt-4.4
  ovirt-4.3:
    - ovirt-4.3

stages:
  - build-artifacts:
      substages:
        - build-py3:
            archs:
              - ppc64le:
                  distributions:
                    - el8stream
                    - rhel8
              - x86_64:
                  distributions:
                    - el8stream
                    - rhel8
  - check-patch:
      archs:
        - x86_64
      substages:
        - install:
            run-if:
              file-changed:
                - 'vdsm.spec.in'
                - '*Makefile.am'
                - 'automation/*'
                - 'build-aux/*'
            distributions:
              - el8stream:
                  runtime-requirements:
                    jenkins_master: ovirt.org
              - rhel8:
                  runtime-requirements:
                    jenkins_master: psi.redhat.com
        - linters:
            distributions:
              - el8stream:
                  runtime-requirements:
                    jenkins_master: all
        - tests-py3:
            distributions:
              - el8stream:
                  runtime-requirements:
                    jenkins_master: ovirt.org
                    host-distro: newer
              - rhel8:
                  runtime-requirements:
                    jenkins_master: psi.redhat.com
        # For now everything runs on both jenkins u/s and PSI.
        # Only PSI provides VM for containers, so in order to trigger PSI only we need to use rhel8
        - tests-container:
            distributions:
              - rhel8:
                  runtime-requirements:
                    jenkins_master: psi.redhat.com
        - nmstate-func-tests: &nmstate-func-tests
            run-if:
              file-changed:
                - 'lib/vdsm/network/*'
                - 'lib/vdsm/common/network/*'
                - 'tests/network/functional/*'
                - 'automation/*.{{ substage }}.*'
            distributions:
              - rhel8:
                  runtime-requirements:
                    jenkins_master: psi.redhat.com
        - nmstate-func-tests-ovs:
            <<: *nmstate-func-tests
